src/chapter6/beans/UserMessage.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class UserMessage implements Serializable {

    private int id;
    private String account;
    private String name;
    private int userId;
    private String text;
    private Date created_date;

    // getter/setterは省略されているので、自分で記述しましょう。
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Date getCreatedDate() {
        return created_date;
    }

    public void setCreatedDate(Date created_date) {
        this.created_date = created_date;
    }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String accountOrEmail = request.getParameter("accountOrEmail");
        String password = request.getParameter("password");

        User user = new UserService().select(accountOrEmail, password);
        if (user == null) {
            List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("ログインに失敗しました");
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");

        User user = new UserService().select(loginUser.getId());

        request.setAttribute("user", user);
        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        //設定画面でポストされてきたユーザー情報をgetUserメソッドでSettingUserに格納。
        User settingUser = getUser(request);
        //上のユーザー情報のうち＠アカウントを引数にしてかぶりがないか判定。
        //かぶりがなく問題なく登録できる場合はnull、あった場合はUser型が一つ帰ってくる。
        User firstUser = new UserService().select(settingUser.getAccount());

        if (isValid(settingUser, firstUser, errorMessages)) {
            try {
                new UserService().update(settingUser);
            } catch (NoRowsUpdatedRuntimeException e) {
                errorMessages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
            }
        }

        if (errorMessages.size() != 0) {
            request.setAttribute("errorMessages", errorMessages);
            //ここちょっと不明！！うまくいかなかったら確認してね！！！
            request.setAttribute("user", settingUser);
            request.getRequestDispatcher("setting.jsp").forward(request, response);
            return;
        }

        session.setAttribute("loginUser", settingUser);
        response.sendRedirect("./");
    }

    //新しいアカウント名などをUser型に格納するメソッド。
    private User getUser(HttpServletRequest request) throws IOException, ServletException {
    	User user = new User();

	    user.setId(Integer.parseInt(request.getParameter("id")));
	    user.setName(request.getParameter("name"));
	    user.setAccount(request.getParameter("account"));
	    user.setPassword(request.getParameter("password"));
	    user.setEmail(request.getParameter("email"));
	    user.setDescription(request.getParameter("description"));

	    return user;
    }
    //バリデーションの追加
    private boolean isValid(User settingUser, User firstUser, List<String> errorMessages) {

        String name = settingUser.getName();
        String account = settingUser.getAccount();
        String email = settingUser.getEmail();

        if (!StringUtils.isBlank(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }
        if (StringUtils.isBlank(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        }
        if(firstUser != null) {
        	 errorMessages.add("アカウント名が重複しています");
        }
        if (!StringUtils.isBlank(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }


}

src/chapter6/controller/SignUpServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        List<String> errorMessages = new ArrayList<String>();

        //登録画面でポストされたユーザー情報を格納
        User signUpUser = getUser(request);
        //上のユーザー情報のうち＠アカウントを引数にしてかぶりがないか判定。
        //かぶりがなく問題なく登録できる場合はnull、あった場合はUser型が一つ帰ってくる。
        User firstUser = new UserService().select(signUpUser.getAccount());
        if (!isValid(signUpUser, firstUser, errorMessages)) {
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("signup.jsp").forward(request, response);
            return;
        }
        new UserService().insert(signUpUser);
        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    private boolean isValid(User signUpUser,User firstUser, List<String> errorMessages) {

    	String name = signUpUser.getName();
        String account = signUpUser.getAccount();
        String password = signUpUser.getPassword();
        String email = signUpUser.getEmail();

        if (!StringUtils.isBlank(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }

        if (StringUtils.isBlank(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        }
        if(firstUser != null){
        	errorMessages.add("アカウント名が重複しています");
        }

        if (StringUtils.isBlank(password)) {
            errorMessages.add("パスワードを入力してください");
        }

        if (!StringUtils.isBlank(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/TopServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.beans.UserMessage;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {
    	
    	//ログアウトした状態のとき（ログイン前）はuserはnull
        boolean isShowMessageForm = false;
        User user = (User) request.getSession().getAttribute("loginUser");
        if (user != null) {
            isShowMessageForm = true;
        }

        String userId = request.getParameter("user_id");
        List<UserMessage> messages = new MessageService().select(userId);

        request.setAttribute("messages", messages);
        request.setAttribute("isShowMessageForm", isShowMessageForm);
        request.getRequestDispatcher("/top.jsp").forward(request, response);
    }
}

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン</title>
    </head>
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="login" method="post"><br />
                <label for="accountOrEmail">アカウント名かメールアドレス</label>
                <input name="accountOrEmail" id="accountOrEmail"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)YourName</div>
        </div>
    </body>
</html>

WebContent/setting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="setting" method="post"><br />
                <input name="id" value="${user.id}" id="id" type="hidden"/>

                <label for="name">名前</label>
                <input name="name" value="${user.name}" id="name"/>（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" value="${user.account}" /><br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <label for="email">メールアドレス</label>
                <input name="email" value="${user.email}" id="email"/> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"><c:out value="${user.description}" /></textarea> <br />

                <input type="submit" value="更新" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>ユーザー登録</title>
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="signup" method="post"><br />
                <label for="name">名前</label>
                <input name="name" id="name" />（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" id="account" /> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /> <br />

                <label for="email">メールアドレス</label>
                <input name="email" id="email" /> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"></textarea> <br />
                <input type="submit" value="登録" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright">Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>簡易Twitter</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
       <div class="header">
    		<c:if test="${ empty loginUser }">
        		<a href="login">ログイン</a>
        		<a href="signup">登録する</a>
    		</c:if>
    		<c:if test="${ not empty loginUser }">
        		<a href="./">ホーム</a>
        		<a href="setting">設定</a>
        		<a href="logout">ログアウト</a>
    		</c:if>
		</div>
		<c:if test="${ not empty loginUser }">
    		<div class="profile">
        		<div class="name"><h2><c:out value="${loginUser.name}" /></h2></div>
        		<div class="account">@<c:out value="${loginUser.account}" /></div>
        		<div class="description"><c:out value="${loginUser.description}" /></div>
    		</div>
		</c:if>
		<c:if test="${ not empty errorMessages }">
    		<div class="errorMessages">
        		<ul>
            		<c:forEach items="${errorMessages}" var="errorMessage">
                		<li><c:out value="${errorMessage}" />
            		</c:forEach>
        		</ul>
    		</div>
    		<c:remove var="errorMessages" scope="session" />
		</c:if>

		<div class="form-area">
    		<c:if test="${ isShowMessageForm }">
        		<form action="message" method="post">
            		いま、どうしてる？<br />
            		<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
            		<br />
            		<input type="submit" value="つぶやく">（140文字まで）
        		</form>
        	</c:if>
        </div>
        <div class="messages">
    		<c:forEach items="${messages}" var="message">
        		<div class="message">
            		<div class="account-name">
                		<span class="account">
                			<a href="./?user_id=<c:out value="${message.userId}"/> ">
        						<c:out value="${message.account}" />
    						</a>
    					</span>
            		</div>
            		<div class="text"><c:out value="${message.text}" /></div>
            		<div class="date"><fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
        		</div>
    		</c:forEach>
		</div>


		<div class="copyright"> Copyright(c)OzekiHonoka</div>
    </body>
</html>